// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5a499c83-4d37-4634-a6b1-469acd4f3c0e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_shpA3V4BD",
    "aws_user_pools_web_client_id": "433e0ijhbbn4hkr181qalu5cfv",
    "aws_user_files_s3_bucket": "glimpzbucket",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
